/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EventRouteImport } from './routes/event'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PrizesRouteImport } from './routes/prizes'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as StatusRouteImport } from './routes/status'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as PaymentIdRouteImport } from './routes/payment.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EventRoute = EventRouteImport.update({
  id: '/event',
  path: '/event',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PrizesRoute = PrizesRouteImport.update({
  id: '/prizes',
  path: '/prizes',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentIdRoute = PaymentIdRouteImport.update({
  id: '/payment/$id',
  path: '/payment/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/event': typeof EventRoute
  '/faq': typeof FaqRoute
  '/prizes': typeof PrizesRoute
  '/register': typeof RegisterRoute
  '/rules': typeof RulesRoute
  '/status': typeof StatusRoute
  '/timeline': typeof TimelineRoute
  '/payment/$id': typeof PaymentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/event': typeof EventRoute
  '/faq': typeof FaqRoute
  '/prizes': typeof PrizesRoute
  '/register': typeof RegisterRoute
  '/rules': typeof RulesRoute
  '/status': typeof StatusRoute
  '/timeline': typeof TimelineRoute
  '/payment/$id': typeof PaymentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/event': typeof EventRoute
  '/faq': typeof FaqRoute
  '/prizes': typeof PrizesRoute
  '/register': typeof RegisterRoute
  '/rules': typeof RulesRoute
  '/status': typeof StatusRoute
  '/timeline': typeof TimelineRoute
  '/payment/$id': typeof PaymentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/event'
    | '/faq'
    | '/prizes'
    | '/register'
    | '/rules'
    | '/status'
    | '/timeline'
    | '/payment/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/event'
    | '/faq'
    | '/prizes'
    | '/register'
    | '/rules'
    | '/status'
    | '/timeline'
    | '/payment/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/event'
    | '/faq'
    | '/prizes'
    | '/register'
    | '/rules'
    | '/status'
    | '/timeline'
    | '/payment/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  EventRoute: typeof EventRoute
  FaqRoute: typeof FaqRoute
  PrizesRoute: typeof PrizesRoute
  RegisterRoute: typeof RegisterRoute
  RulesRoute: typeof RulesRoute
  StatusRoute: typeof StatusRoute
  TimelineRoute: typeof TimelineRoute
  PaymentIdRoute: typeof PaymentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event': {
      id: '/event'
      path: '/event'
      fullPath: '/event'
      preLoaderRoute: typeof EventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prizes': {
      id: '/prizes'
      path: '/prizes'
      fullPath: '/prizes'
      preLoaderRoute: typeof PrizesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/$id': {
      id: '/payment/$id'
      path: '/payment/$id'
      fullPath: '/payment/$id'
      preLoaderRoute: typeof PaymentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  EventRoute: EventRoute,
  FaqRoute: FaqRoute,
  PrizesRoute: PrizesRoute,
  RegisterRoute: RegisterRoute,
  RulesRoute: RulesRoute,
  StatusRoute: StatusRoute,
  TimelineRoute: TimelineRoute,
  PaymentIdRoute: PaymentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
