/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CertificateRouteImport } from './routes/certificate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EventRouteImport } from './routes/event'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PrizesRouteImport } from './routes/prizes'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as StatusRouteImport } from './routes/status'
import { Route as Sys9f4c2aRouteImport } from './routes/sys-9f4c2a'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as PaymentIdRouteImport } from './routes/payment.$id'
import { Route as AuthenticatedCKRouteImport } from './routes/_authenticated/c.$k'
import { Route as AuthenticatedCKIndexRouteImport } from './routes/_authenticated/c.$k.index'
import { Route as AuthenticatedCKCertificatesRouteImport } from './routes/_authenticated/c.$k.certificates'
import { Route as AuthenticatedCKContentRouteImport } from './routes/_authenticated/c.$k.content'
import { Route as AuthenticatedCKLogsRouteImport } from './routes/_authenticated/c.$k.logs'
import { Route as AuthenticatedCKMessagesRouteImport } from './routes/_authenticated/c.$k.messages'
import { Route as AuthenticatedCKRegistrationsRouteImport } from './routes/_authenticated/c.$k.registrations'
import { Route as AuthenticatedCKSettingsRouteImport } from './routes/_authenticated/c.$k.settings'
import { Route as AuthenticatedCKTextsRouteImport } from './routes/_authenticated/c.$k.texts'
import { Route as AuthenticatedCKUsersRouteImport } from './routes/_authenticated/c.$k.users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificateRoute = CertificateRouteImport.update({
  id: '/certificate',
  path: '/certificate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EventRoute = EventRouteImport.update({
  id: '/event',
  path: '/event',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PrizesRoute = PrizesRouteImport.update({
  id: '/prizes',
  path: '/prizes',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const Sys9f4c2aRoute = Sys9f4c2aRouteImport.update({
  id: '/sys-9f4c2a',
  path: '/sys-9f4c2a',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentIdRoute = PaymentIdRouteImport.update({
  id: '/payment/$id',
  path: '/payment/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCKRoute = AuthenticatedCKRouteImport.update({
  id: '/c/$k',
  path: '/c/$k',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCKIndexRoute = AuthenticatedCKIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedCKRoute,
} as any)
const AuthenticatedCKCertificatesRoute =
  AuthenticatedCKCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => AuthenticatedCKRoute,
  } as any)
const AuthenticatedCKContentRoute = AuthenticatedCKContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AuthenticatedCKRoute,
} as any)
const AuthenticatedCKLogsRoute = AuthenticatedCKLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedCKRoute,
} as any)
const AuthenticatedCKMessagesRoute = AuthenticatedCKMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedCKRoute,
} as any)
const AuthenticatedCKRegistrationsRoute =
  AuthenticatedCKRegistrationsRouteImport.update({
    id: '/registrations',
    path: '/registrations',
    getParentRoute: () => AuthenticatedCKRoute,
  } as any)
const AuthenticatedCKSettingsRoute = AuthenticatedCKSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedCKRoute,
} as any)
const AuthenticatedCKTextsRoute = AuthenticatedCKTextsRouteImport.update({
  id: '/texts',
  path: '/texts',
  getParentRoute: () => AuthenticatedCKRoute,
} as any)
const AuthenticatedCKUsersRoute = AuthenticatedCKUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedCKRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/certificate': typeof CertificateRoute
  '/contact': typeof ContactRoute
  '/event': typeof EventRoute
  '/faq': typeof FaqRoute
  '/prizes': typeof PrizesRoute
  '/register': typeof RegisterRoute
  '/rules': typeof RulesRoute
  '/status': typeof StatusRoute
  '/sys-9f4c2a': typeof Sys9f4c2aRoute
  '/timeline': typeof TimelineRoute
  '/p/$slug': typeof PSlugRoute
  '/payment/$id': typeof PaymentIdRoute
  '/c/$k': typeof AuthenticatedCKRouteWithChildren
  '/c/$k/certificates': typeof AuthenticatedCKCertificatesRoute
  '/c/$k/content': typeof AuthenticatedCKContentRoute
  '/c/$k/logs': typeof AuthenticatedCKLogsRoute
  '/c/$k/messages': typeof AuthenticatedCKMessagesRoute
  '/c/$k/registrations': typeof AuthenticatedCKRegistrationsRoute
  '/c/$k/settings': typeof AuthenticatedCKSettingsRoute
  '/c/$k/texts': typeof AuthenticatedCKTextsRoute
  '/c/$k/users': typeof AuthenticatedCKUsersRoute
  '/c/$k/': typeof AuthenticatedCKIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/certificate': typeof CertificateRoute
  '/contact': typeof ContactRoute
  '/event': typeof EventRoute
  '/faq': typeof FaqRoute
  '/prizes': typeof PrizesRoute
  '/register': typeof RegisterRoute
  '/rules': typeof RulesRoute
  '/status': typeof StatusRoute
  '/sys-9f4c2a': typeof Sys9f4c2aRoute
  '/timeline': typeof TimelineRoute
  '/p/$slug': typeof PSlugRoute
  '/payment/$id': typeof PaymentIdRoute
  '/c/$k/certificates': typeof AuthenticatedCKCertificatesRoute
  '/c/$k/content': typeof AuthenticatedCKContentRoute
  '/c/$k/logs': typeof AuthenticatedCKLogsRoute
  '/c/$k/messages': typeof AuthenticatedCKMessagesRoute
  '/c/$k/registrations': typeof AuthenticatedCKRegistrationsRoute
  '/c/$k/settings': typeof AuthenticatedCKSettingsRoute
  '/c/$k/texts': typeof AuthenticatedCKTextsRoute
  '/c/$k/users': typeof AuthenticatedCKUsersRoute
  '/c/$k': typeof AuthenticatedCKIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/certificate': typeof CertificateRoute
  '/contact': typeof ContactRoute
  '/event': typeof EventRoute
  '/faq': typeof FaqRoute
  '/prizes': typeof PrizesRoute
  '/register': typeof RegisterRoute
  '/rules': typeof RulesRoute
  '/status': typeof StatusRoute
  '/sys-9f4c2a': typeof Sys9f4c2aRoute
  '/timeline': typeof TimelineRoute
  '/p/$slug': typeof PSlugRoute
  '/payment/$id': typeof PaymentIdRoute
  '/_authenticated/c/$k': typeof AuthenticatedCKRouteWithChildren
  '/_authenticated/c/$k/certificates': typeof AuthenticatedCKCertificatesRoute
  '/_authenticated/c/$k/content': typeof AuthenticatedCKContentRoute
  '/_authenticated/c/$k/logs': typeof AuthenticatedCKLogsRoute
  '/_authenticated/c/$k/messages': typeof AuthenticatedCKMessagesRoute
  '/_authenticated/c/$k/registrations': typeof AuthenticatedCKRegistrationsRoute
  '/_authenticated/c/$k/settings': typeof AuthenticatedCKSettingsRoute
  '/_authenticated/c/$k/texts': typeof AuthenticatedCKTextsRoute
  '/_authenticated/c/$k/users': typeof AuthenticatedCKUsersRoute
  '/_authenticated/c/$k/': typeof AuthenticatedCKIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/certificate'
    | '/contact'
    | '/event'
    | '/faq'
    | '/prizes'
    | '/register'
    | '/rules'
    | '/status'
    | '/sys-9f4c2a'
    | '/timeline'
    | '/p/$slug'
    | '/payment/$id'
    | '/c/$k'
    | '/c/$k/certificates'
    | '/c/$k/content'
    | '/c/$k/logs'
    | '/c/$k/messages'
    | '/c/$k/registrations'
    | '/c/$k/settings'
    | '/c/$k/texts'
    | '/c/$k/users'
    | '/c/$k/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/certificate'
    | '/contact'
    | '/event'
    | '/faq'
    | '/prizes'
    | '/register'
    | '/rules'
    | '/status'
    | '/sys-9f4c2a'
    | '/timeline'
    | '/p/$slug'
    | '/payment/$id'
    | '/c/$k/certificates'
    | '/c/$k/content'
    | '/c/$k/logs'
    | '/c/$k/messages'
    | '/c/$k/registrations'
    | '/c/$k/settings'
    | '/c/$k/texts'
    | '/c/$k/users'
    | '/c/$k'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/certificate'
    | '/contact'
    | '/event'
    | '/faq'
    | '/prizes'
    | '/register'
    | '/rules'
    | '/status'
    | '/sys-9f4c2a'
    | '/timeline'
    | '/p/$slug'
    | '/payment/$id'
    | '/_authenticated/c/$k'
    | '/_authenticated/c/$k/certificates'
    | '/_authenticated/c/$k/content'
    | '/_authenticated/c/$k/logs'
    | '/_authenticated/c/$k/messages'
    | '/_authenticated/c/$k/registrations'
    | '/_authenticated/c/$k/settings'
    | '/_authenticated/c/$k/texts'
    | '/_authenticated/c/$k/users'
    | '/_authenticated/c/$k/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  CertificateRoute: typeof CertificateRoute
  ContactRoute: typeof ContactRoute
  EventRoute: typeof EventRoute
  FaqRoute: typeof FaqRoute
  PrizesRoute: typeof PrizesRoute
  RegisterRoute: typeof RegisterRoute
  RulesRoute: typeof RulesRoute
  StatusRoute: typeof StatusRoute
  Sys9f4c2aRoute: typeof Sys9f4c2aRoute
  TimelineRoute: typeof TimelineRoute
  PSlugRoute: typeof PSlugRoute
  PaymentIdRoute: typeof PaymentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificate': {
      id: '/certificate'
      path: '/certificate'
      fullPath: '/certificate'
      preLoaderRoute: typeof CertificateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event': {
      id: '/event'
      path: '/event'
      fullPath: '/event'
      preLoaderRoute: typeof EventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prizes': {
      id: '/prizes'
      path: '/prizes'
      fullPath: '/prizes'
      preLoaderRoute: typeof PrizesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sys-9f4c2a': {
      id: '/sys-9f4c2a'
      path: '/sys-9f4c2a'
      fullPath: '/sys-9f4c2a'
      preLoaderRoute: typeof Sys9f4c2aRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/$id': {
      id: '/payment/$id'
      path: '/payment/$id'
      fullPath: '/payment/$id'
      preLoaderRoute: typeof PaymentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/c/$k': {
      id: '/_authenticated/c/$k'
      path: '/c/$k'
      fullPath: '/c/$k'
      preLoaderRoute: typeof AuthenticatedCKRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/c/$k/': {
      id: '/_authenticated/c/$k/'
      path: '/'
      fullPath: '/c/$k/'
      preLoaderRoute: typeof AuthenticatedCKIndexRouteImport
      parentRoute: typeof AuthenticatedCKRoute
    }
    '/_authenticated/c/$k/certificates': {
      id: '/_authenticated/c/$k/certificates'
      path: '/certificates'
      fullPath: '/c/$k/certificates'
      preLoaderRoute: typeof AuthenticatedCKCertificatesRouteImport
      parentRoute: typeof AuthenticatedCKRoute
    }
    '/_authenticated/c/$k/content': {
      id: '/_authenticated/c/$k/content'
      path: '/content'
      fullPath: '/c/$k/content'
      preLoaderRoute: typeof AuthenticatedCKContentRouteImport
      parentRoute: typeof AuthenticatedCKRoute
    }
    '/_authenticated/c/$k/logs': {
      id: '/_authenticated/c/$k/logs'
      path: '/logs'
      fullPath: '/c/$k/logs'
      preLoaderRoute: typeof AuthenticatedCKLogsRouteImport
      parentRoute: typeof AuthenticatedCKRoute
    }
    '/_authenticated/c/$k/messages': {
      id: '/_authenticated/c/$k/messages'
      path: '/messages'
      fullPath: '/c/$k/messages'
      preLoaderRoute: typeof AuthenticatedCKMessagesRouteImport
      parentRoute: typeof AuthenticatedCKRoute
    }
    '/_authenticated/c/$k/registrations': {
      id: '/_authenticated/c/$k/registrations'
      path: '/registrations'
      fullPath: '/c/$k/registrations'
      preLoaderRoute: typeof AuthenticatedCKRegistrationsRouteImport
      parentRoute: typeof AuthenticatedCKRoute
    }
    '/_authenticated/c/$k/settings': {
      id: '/_authenticated/c/$k/settings'
      path: '/settings'
      fullPath: '/c/$k/settings'
      preLoaderRoute: typeof AuthenticatedCKSettingsRouteImport
      parentRoute: typeof AuthenticatedCKRoute
    }
    '/_authenticated/c/$k/texts': {
      id: '/_authenticated/c/$k/texts'
      path: '/texts'
      fullPath: '/c/$k/texts'
      preLoaderRoute: typeof AuthenticatedCKTextsRouteImport
      parentRoute: typeof AuthenticatedCKRoute
    }
    '/_authenticated/c/$k/users': {
      id: '/_authenticated/c/$k/users'
      path: '/users'
      fullPath: '/c/$k/users'
      preLoaderRoute: typeof AuthenticatedCKUsersRouteImport
      parentRoute: typeof AuthenticatedCKRoute
    }
  }
}

interface AuthenticatedCKRouteChildren {
  AuthenticatedCKCertificatesRoute: typeof AuthenticatedCKCertificatesRoute
  AuthenticatedCKContentRoute: typeof AuthenticatedCKContentRoute
  AuthenticatedCKLogsRoute: typeof AuthenticatedCKLogsRoute
  AuthenticatedCKMessagesRoute: typeof AuthenticatedCKMessagesRoute
  AuthenticatedCKRegistrationsRoute: typeof AuthenticatedCKRegistrationsRoute
  AuthenticatedCKSettingsRoute: typeof AuthenticatedCKSettingsRoute
  AuthenticatedCKTextsRoute: typeof AuthenticatedCKTextsRoute
  AuthenticatedCKUsersRoute: typeof AuthenticatedCKUsersRoute
  AuthenticatedCKIndexRoute: typeof AuthenticatedCKIndexRoute
}

const AuthenticatedCKRouteChildren: AuthenticatedCKRouteChildren = {
  AuthenticatedCKCertificatesRoute: AuthenticatedCKCertificatesRoute,
  AuthenticatedCKContentRoute: AuthenticatedCKContentRoute,
  AuthenticatedCKLogsRoute: AuthenticatedCKLogsRoute,
  AuthenticatedCKMessagesRoute: AuthenticatedCKMessagesRoute,
  AuthenticatedCKRegistrationsRoute: AuthenticatedCKRegistrationsRoute,
  AuthenticatedCKSettingsRoute: AuthenticatedCKSettingsRoute,
  AuthenticatedCKTextsRoute: AuthenticatedCKTextsRoute,
  AuthenticatedCKUsersRoute: AuthenticatedCKUsersRoute,
  AuthenticatedCKIndexRoute: AuthenticatedCKIndexRoute,
}

const AuthenticatedCKRouteWithChildren = AuthenticatedCKRoute._addFileChildren(
  AuthenticatedCKRouteChildren,
)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCKRoute: typeof AuthenticatedCKRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCKRoute: AuthenticatedCKRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  CertificateRoute: CertificateRoute,
  ContactRoute: ContactRoute,
  EventRoute: EventRoute,
  FaqRoute: FaqRoute,
  PrizesRoute: PrizesRoute,
  RegisterRoute: RegisterRoute,
  RulesRoute: RulesRoute,
  StatusRoute: StatusRoute,
  Sys9f4c2aRoute: Sys9f4c2aRoute,
  TimelineRoute: TimelineRoute,
  PSlugRoute: PSlugRoute,
  PaymentIdRoute: PaymentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
